#ddev-generated
services:
  apache-solr:
    container_name: ddev-${DDEV_SITENAME}-apache-solr
    hostname: ${DDEV_SITENAME}-apache-solr
    image: solr:9.4
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8983
      - HTTPS_EXPOSE=8984:8983
      # For setup steps see https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Solr/ConfigurationStructures.html#setup-steps
      - SOLR_ENABLE_REMOTE_STREAMING=true
      - SOLR_ENABLE_STREAM_BODY=true
    volumes:
      - "apache-solr:/var/solr/"
      - ".:/mnt/ddev_config"
  web:
    links:
      - apache-solr
volumes:
  apache-solr:
