#ddev-generated

solr_config: 'vendor/apache-solr-for-typo3/solr/Resources/Private/Solr/solr.xml'
configset: 'vendor/apache-solr-for-typo3/solr/Resources/Private/Solr/configsets/ext_solr_12_0_0/'
cores:
  - name: "core_en"
    schema: "english/schema.xml"
  - name: "core_de"
    schema: "german/schema.xml"
